// Minimal stub for DefaultFirebaseOptions used in tests.
// Replace with real values generated by `flutterfire configure` in production.

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
        apiKey: 'FAKE_API_KEY',
        appId: '1:000:android:000',
        messagingSenderId: '000',
        projectId: 'fake-project',
      );
}
